name: ci

on:
  pull_request:
    branches:
      - 'master'
      - 'develop'
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: { java-version: 1.17 }
      - name: Run tests
        run: |
          ./gradlew test

  detekt:
    name: Detekt
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up our JDK environment
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run detekt Linter
        run: ./gradlew detekt


  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: {java-version: 1.17}
      - name: Build release APK and AAB after test
        run: |
          ./gradlew assembleDebug
          ./gradlew bundleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload AAB Bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.aab
          path: app/build/outputs/bundle/debug/app-debug.aab